### ISSUE TITLE
ivy-switch-buffer errors with "Error in post-command-hook (ivy--queue-exhibit): (void-function when-let*)"

### ISSUE THREAD

**Issue by hyOzd** [Yevgnen/ivy-rich#101]
After a recent package update ivy-switch-buffer doesn't work on my setup with ivy-rich-mode. It errors with this message and drops to emacs default prompt:

`Error in post-command-hook (ivy--queue-exhibit): (void-function when-let*)`

Other commands seem to work fine, such as M-x and find-file. When I disable `ivy-rich-mode`, ivy-switch-buffer works too.

I tried force recompiling my package directory as this solved my problems with some other packages after the update.

Emacs version: 25.3.2
ivy: 20210109.1619
ivy-rich: 20201224.4

**Comment by Yevgnen** [comment]
Hi, sorry for the super late reply. Do you have a `when-let` in emacs 25? I've just changed back the `when-let*` to `when-let` in that change. Please try the master branch.

**Comment by hyOzd** [comment]
@Yevgnen Yes there is `when-let` in emac 25.

```when-let is a Lisp macro.

(when-let BINDINGS &rest BODY)

Process BINDINGS and if all values are non-nil eval BODY.
Argument BINDINGS is a list of tuples whose car is a symbol to be
bound and (optionally) used in BODY, and its cadr is a sexp to be
evalled to set symbol’s value.  In the special case you only want
to bind a single value, BINDINGS can just be a plain tuple.
```

I've tried latest version from elpa (20210125.19). It works now. I think issue is solved.
Thanks for the fix.
