### ISSUE TITLE
evenp not found in Emacs 28

### ISSUE THREAD

**Issue by BooAA** [Yevgnen/ivy-rich#103]
Hi, thanks for the work of this awesome package.

When I tried to use `ivy-rich-modify-column` to customize how annotation is shown, I got error `(void-function evenp)`. I'm using Emacs 28 master branch. I don't know whether same error happen in other version of Emacs, maybe we can use `cl-evenp` to make sure it works everywhere.

**Comment by Yevgnen** [comment]
Thanks for the kind words and sorry for late reply. I've pushed a commit for this in master.

**Comment by BooAA** [comment]
Great! I'll close the issue.
