### ISSUE TITLE
'ivy-rich-counsel-function-docstring' does not remove ':advice' thing

### ISSUE THREAD

**Issue by vconcat** [Yevgnen/ivy-rich#104]
```
(use-package ivy
  :hook (after-init . ivy-mode))

(use-package counsel
  :hook (ivy-mode . counsel-mode))

(use-package ivy-rich
  :hook (ivy-mode . ivy-rich-mode))
```

Emacs: 27.1

`M-x counsel-describe-function`

If I replace the regexp in `ivy-rich-counsel-function-docstring` with [this](https://github.com/minad/marginalia/blob/51f750994aaa0b6798d97366acfb0d397639af66/marginalia.el#L355), it display the original doc correctly.

FYI, https://github.com/minad/marginalia/issues/19

**Comment by Yevgnen** [comment]
Thanks for reporting the issue. I gonna steal that regex...

**Comment by vconcat** [comment]
Thanks.
