### ISSUE TITLE
Please，How to set it like this？

### ISSUE THREAD

**Issue by yyangdid** [Yevgnen/ivy-rich#106]
Please，How to set it like this：
![Snipaste_2021-04-07_16-53-50](https://user-images.githubusercontent.com/10922667/113838970-dbf9de00-97c1-11eb-890e-0ba19401dd99.png)

**Comment by Yevgnen** [comment]
Hi, 

Unfortunately, as stated [here](https://github.com/Yevgnen/ivy-rich#important-changes), the support for virtual buffers is dropped in the very [old days](https://github.com/Yevgnen/ivy-rich/commit/604fa2308464186a9867cc6c0ef4235f0377f0e6) and currently not haven't been added back. You need to write you own custom transformers at the moment for handling virtual buffers. I almost forgot that part, but I will take a look into it when I have time.

**Comment by yyangdid** [comment]
OK, Thank you. Nice package 👍
