### ISSUE TITLE
ivy-rich-switch-buffer-path not shown when switching buffers

### ISSUE THREAD

**Issue by EverardNisse** [Yevgnen/ivy-rich#108]
Even on a fresh emacs install, switching buffers with C-x b does not show the path and project columns with ivy-switch-buffer. The space for the data seems to be reserved but blank. Changing themes or ivy-rich variables (like switching column order, width, path abbreviation, etc) does not seem to have an effect. Ivy-rich-mode was cycled after changes when testing.

**Comment by Yevgnen** [comment]
What does your config look like? Can you provide a reproducing script?

**Comment by EverardNisse** [comment]
Sorry for the delay. The most minimal setup I can get is:
1. Start emacs with "env HOME=~/test emacs"
2. Evaluate to add Melpa
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
```
3. M-x package-install ivy, counsel, ivy-rich
4. M-x ivy-mode, ivy-rich-mode
5. C-x b

At which point I'd expect to see paths in the blank spaces.
![Screenshot_20210515_104502](https://user-images.githubusercontent.com/77442297/118354269-d9756b80-b559-11eb-8e19-0884736bc596.png)

**Comment by EverardNisse** [comment]
That is an excellent catch @avexs. Hope a variation gets merged, until then using your override.
