### ISSUE TITLE
MELPA-stable snapshot is broken with ivy 0.14.0

### ISSUE THREAD

**Issue by xgqt** [Yevgnen/ivy-rich#118]
The snapshot on MELPA-stable is very old, it's the last tag, so back in 2020, that version uses some functions removed from ivy 0.14.0.

I use `ivy-rich` from Gentoo which has a fixed snapshot so I did not realize my config is broken on systems using MELPA stable.

Below is a OpenSUSE VM using MELPA stable repository:
![image](https://user-images.githubusercontent.com/47485207/233749467-22d0f078-f632-4bdc-bf8d-80dcd0c2badd.png)

Please create a new tag to regenerate the MELPA stable snapshot. Thanks in advance!

**Comment by Yevgnen** [comment]
Hi, I've create a new tag. 

Please try later when the rebuilding of Melpa is finished. 

Sorry for the inconvenience. I didn't notice that version is broken on stable Melpa.

**Comment by xgqt** [comment]
The new version from git 0.1.7 works well. I do not see it available on MELPA-stable yet but it should get there. Thanks a lot!
