### ISSUE TITLE
With ivy-rich, ivy-switch-buffer crashes when there is a buffer created via browse-url-emacs

### ISSUE THREAD

**Issue by emacswatcher** [Yevgnen/ivy-rich#14]
To recreate:
M-x browse-url-emacs RET https://raw.githubusercontent.com/Yevgnen/ivy-rich/master/ivy-rich.el
then, with ivy-rich loaded, invoke ivy-switch-buffer

The command completes without any onscreen effects with the following message:

file-truename: Apparent cycle of symbolic links for https:

Ivy-switch-buffer works for this example without ivy-rich loaded.

**Comment by Yevgnen** [comment]
Hi, I can confirm this issue. I will fix it as soon as possible.

**Comment by Yevgnen** [comment]
It should work now, please wait for the elpa update and let me know if there's any problem :)

**Comment by emacswatcher** [comment]
Thanks for the quick fix. 

Closing for all the right reasons.
