### ISSUE TITLE
How can I make ivy-rich always show the full path of a file buffer

### ISSUE THREAD

**Issue by amosbird** [Yevgnen/ivy-rich#15]
I've set ` '(ivy-rich-abbreviate-paths nil)` but it doesn't do what I need.

![image](https://user-images.githubusercontent.com/5085485/31903065-99ba9c86-b7ec-11e7-922e-227b50ee9635.png)

**Comment by Yevgnen** [comment]
Hi, by full path, do you mean absolute path? Currently it shows the path relative to the project root, but I am glad to add the absolute path option later though it's a bit long for me.😆

**Comment by amosbird** [comment]
Ah, OK.

**Comment by Yevgnen** [comment]
Hi, sorry for late reply. You can now set `ivy-rich-path-style` to `'full` or `'absolute` to have absolute path displaying. There may take some time for elpa to update.

**Comment by amosbird** [comment]
Thanks!
