### ISSUE TITLE
broken ivy-avy

### ISSUE THREAD

**Issue by tmdmelo** [Yevgnen/ivy-rich#16]
`ivy-avy` doesn't work as expected with `ivy-rich`. It opens a buffer named as the whole line content instead of the expected buffer. For example, trying to open the `*scratch*` buffer would instead open a buffer named like `*scratch*                         1.1k    Lisp Interaction               /home/user/`.

To reproduce (assuming package `avy` is installed):
- `M-x ivy-switch-buffer RET`
- `C-'` (the default keybinding for `ivy-avy`)
- Press one or more keys as needed to pick a candidate

I'll send a PR to upstream with a proposed fix for `ivy-avy`, that will also fix this issue.

**Comment by Yevgnen** [comment]
Sorry for late reply. I can reproduce it. I don't know about `ivy-avy` before. 😓 I'll take a look into it later.

**Comment by tmdmelo** [comment]
No worries. My PR abo-abo/swiper#1256 has been accepted. This issue is fixed as of abo-abo/swiper@1a33da4be117f5a6757ec94c42996979249373d7. I just thought it would be relevant to document it here too.
