### ISSUE TITLE
Slowdown when using Tramp

### ISSUE THREAD

**Issue by jwiegley** [Yevgnen/ivy-rich#23]
I've found that if I have several files open via Tramp, `ivy-rich` slows down considerably, taking up to 10 seconds sometimes to show a buffer selection prompt. I wonder if there's a way to not query for certain details when the path is a remote one? Other than that, love this mode!

**Comment by Yevgnen** [comment]
Hi, that's a known issue due to some functions like `projectile-project-root` does not work quite well under `tramp`. I'm also facing this when opening some files in a remote server though in a local server it's fast enough. I'll add an custom option to this later!

**Comment by Yevgnen** [comment]
I've added a flag `ivy-rich-parse-remote-buffer` to toggle the parse for remote files. Please wait for elpa update and check :)

**Comment by jwiegley** [comment]
Thanks!

**Comment by jwiegley** [comment]
@Yevgnen Note that for me, this causes the 4th column (pathname) to disappear for local files too.

**Comment by Yevgnen** [comment]
@jwiegley Sorry. I made a stupid mistake. I've fixed this and it should be fixed in the next build.

**Comment by jwiegley** [comment]
@Yevgnen Thanks!  I really like ivy-rich, btw. :)

**Comment by Yevgnen** [comment]
I'll try to find a better way to handling this, thanks for the feedback.

**Comment by seagle0128** [comment]
Sorry for comment here.
I am also experiencing the same issue, even set `ivy-rich-parse-remote-buffer` to nil.

**Comment by Yevgnen** [comment]
@seagle0128 Does the issue exist if you remove the columns related to `projectile` and `tramp`? It maybe due the project root look up in `projectile`. Currently known possible solution includes setting projectile cache, modifying `projectile-project-root-files-functions`, or replace `projectile` with some other systems like `project.el` or `ffip`. I tried `project.el` just now, it was slower thought. Suggestions are welcome and feel free to open a new issue of it.

**Comment by seagle0128** [comment]
@Yevgnen RIght! It's because of `projectile` calls. I did profile successfully today and attached below. I don't think `project` helps a lot. It's deserved to try changing `projectile-project-root-files-functions`.

![image](https://user-images.githubusercontent.com/140797/50920075-676b5400-147f-11e9-80cb-eaf5e31504f8.png)

**Comment by seagle0128** [comment]
> Updated: Also, there are some calls to `file-truename` in `ivy-rich-switch-buffer-path` which known to be slow. If you have any suggestion of reducing these calls or a better implementation, please let me know!

`file-true-name` has bad performance, especially for the remote files. It's much faster to handle local files.  In `doom-modeline`, I converted all remote files path to the local path, and add hostname later.
