### ISSUE TITLE
Buffer name and path are not truncated correctly

### ISSUE THREAD

**Issue by yangsheng6810** [Yevgnen/ivy-rich#26]
When buffer name is too long, it takes more space than indicated by `ivy-rich-switch-buffer-name-max-length`, as shown in the following picture:
![normal_buffer](https://user-images.githubusercontent.com/2863729/37370519-d570bc14-26e2-11e8-8090-9d5b2b3ca620.png)
Problem comes from function `ivy-rich-switch-buffer-pad`, which pads `str` to approprate length, but does nothing if it is longer than `len` (I assume it is where truncation should be handled).

Another problem is for virtual buffers, the length of project path is not calculated correctly, as shown in the following picture:
![virtual_buffer](https://user-images.githubusercontent.com/2863729/37370794-a67b3ed8-26e3-11e8-8b7c-c821fcc90208.png)
A fix would be replacing the second call of `(window-width)` in function `ivy-rich-switch-buffer-virtual-buffer` with `(window-width (minibuffer-window))`, as in the first call.

Here is my sample fix
```diff
--- ivy-rich.el	2018-03-13 17:30:57.518670083 -0400
+++ ivy-rich_new.el	2018-03-13 17:30:52.438640122 -0400
@@ -133,7 +133,9 @@
       (if left
           (concat (make-string (- len (length str)) ? ) str)
         (concat str (make-string (- len (length str)) ? )))
-    str))
+    (if (> (length str) len)
+        (format "%s..." (substring str 0 (- len 3)))
+      str)))
 
 (defun ivy-rich-switch-buffer-user-buffer-p (buffer)
   "Check whether BUFFER-NAME is a user buffer."
@@ -289,7 +291,7 @@
          (filename (propertize filename 'face 'ivy-virtual))
          (path (file-name-directory str))
          (path (ivy-rich-switch-buffer-shorten-path path (- (window-width (minibuffer-window)) (length filename))))
-         (path (ivy-rich-switch-buffer-pad path (- (window-width)
+         (path (ivy-rich-switch-buffer-pad path (- (window-width (minibuffer-window))
                                                    (length filename)
                                                    2)))  ; Fixed the unexpected wrapping in terminal
          (path (propertize path 'face 'ivy-virtual)))
```

**Comment by Yevgnen** [comment]
Thanks. Should fixed in the next elpa update.
