### ISSUE TITLE
Customizing the columns

### ISSUE THREAD

**Issue by tautologyclub** [Yevgnen/ivy-rich#29]
Hi,

Really cool package! I was wondering however, why isn't there an easier way to customize which columns get displayed? Basically I don't see myself caring about buffer size that much, and buffer type (or whatever it is, the column showing *&, !, *, etc) is a bit overkill for me too.

There's no defcustom for this, but I wouldn't mind hacking it by overriding some defun if that's what it takes. Any advice is appreciated here.

**Comment by Yevgnen** [comment]
Hi, thanks for the kind words. Column customization is on the plan, but not right now though...I'll work on it as soon as possible.

**Comment by seagle0128** [comment]
Vote it. Add it's better customize faces as well.

**Comment by Yevgnen** [comment]
@tautologyclub You can test the customizable version in `customize` branch now. Feedback is welcomed.
