### ISSUE TITLE
problem: defer loading of ivy-rich with use-package

### ISSUE THREAD

**Issue by bymoz089** [Yevgnen/ivy-rich#35]
I'm testing the current customize tree.  
I try to defer loading of `ivy-rich` with help of `use-package`.    
*Note* that in my config `ivy`, `counsel`, `swiper` and `amx` are also deferred via use-package and will only be initialized on key press (like `M-x` for `counsel-M-x` or `C-s` for `swiper`)

    (use-package ivy-rich
    	:after (counsel)
    	:config
     	(setq ivy-rich--original-display-transformers-list nil)  ;; needs to be set otherwise (ivy-rich-set-display-transformer) does not get called
    	(ivy-rich-mode 1) 
    	)

With this `use-package` config it is important to set  `ivy-rich--original-display-transformers-list` to `nil` before calling `(ivy-rich-mode 1)`, otherwise `ivy-rich-set-display-transformer` does not get called, thus resulting in an active `ivy-rich minor-mode` without functionality of `ivy-rich`.

**Comment by Yevgnen** [comment]
Hi, in the testing branch, loading `ivy-rich` will load the required packages if the related commands are defined in `ivy-rich--display-transformers-list`. Otherwise, the transformer will be overwritten by default after the package is loaded.

You don't need to set `ivy-rich-mode` to `t`. Using `(ivy-rich-mode 1)` will set it automatically. Since you enabling the minor mode twice, `ivy-rich--original-display-transformers-list` is not `nil` before the second time you try to enable it.

I will also find a way to prevent this systematically. Thanks for the feedback!

**Comment by Yevgnen** [comment]
Hi, 

`ivy-rich--original-display-transformers-list` should be `nil` before enabling the minor mode. I guess the minor mode is enabled somewhere twice?

**Comment by bymoz089** [comment]
Without setting `ivy-rich--original-display-transformers-list` myself: the line `(ivy-rich-mode 1)` enables `ivy-rich`. \\
The value of `ivy-rich-mode` is then true, but `ivy-rich` is not properly initialized. Doing `M-x ivy-rich-mode` twice (first disable then enable) fixes this. 

`ivy-rich` is nowhere else mentioned in my init.el and I can't see an error within this `use-package` configuration of `ivy-rich`.

**Comment by Guilz** [comment]
With the following `use-package` directive and the current `melpa-stable` version of `ivy-rich`:

```elisp
(use-package ivy-rich
  :ensure t
  :config
  (setq ivy-rich--original-display-transformers-list nil)  ;; needs to be set otherwise (ivy-rich-set-display-transformer) does not get called
  (ivy-set-display-transformer 'ivy-switch-buffer
                               'ivy-rich-switch-buffer-transformer)
  (setq-default ivy-rich-path-style 'abbrev
                ivy-virtual-abbreviate 'full
                ivy-rich-switch-buffer-align-virtual-buffer t))

```

I get the following error when trying to use `C-x b`: `mapcar: Symbol’s function definition is void: ivy-rich-switch-buffer-transformer`.

Interactively turning off and back on `ivy-rich-mode` (with `M-x`) solves the problem, but it's not convenient at all.

Any chance this can be fixed soon?

**Comment by Yevgnen** [comment]
@Guilz Hi, `ivy-rich-switch-buffer-transformer` is deprecated since version `0.1.0`. Also you don't need to set the display transformer manually, just do `(ivy-rich-mode 1)`.

You should change your config to

```
(use-package ivy-rich
  :ensure t
  :after (ivy)
  :init
  (setq ivy-rich-path-style 'abbrev
        ivy-virtual-abbreviate 'full)
  :config (ivy-rich-mode 1))```

That works fine for me in a `-Q -l .emacs` session.

**Comment by Guilz** [comment]
Thank you for this explanation, it works just fine now. I guess I should read release notes...
