### ISSUE TITLE
use with all-the-icons-ivy?

### ISSUE THREAD

**Issue by emacsomancer** [Yevgnen/ivy-rich#37]
Is there any way of using this package with [all-the-icons-ivy](https://github.com/asok/all-the-icons-ivy)?

**Comment by Yevgnen** [comment]
Hi, I think it should be pretty easy to define custom columns if you are using the [customize](https://github.com/Yevgnen/ivy-rich/tree/customize) branch though currently I haven't merged it. You can simply define a column function (which receive the candidate as argument and should return a transformed string)

```elisp
(defun ivy-rich-switch-buffer-icon (candidate)
  (with-current-buffer
      (get-buffer candidate)
    (all-the-icons-icon-for-mode major-mode)))
```

and add it to the transformer settings like

```elisp
(setq ivy-rich--display-transformers-list
      '(ivy-switch-buffer
        (:columns
         ((ivy-rich-switch-buffer-icon :width 2)
          (ivy-rich-candidate (:width 30))
          (ivy-rich-switch-buffer-size (:width 7))
          (ivy-rich-switch-buffer-indicators (:width 4 :face error :align right))
          (ivy-rich-switch-buffer-major-mode (:width 12 :face warning))
          (ivy-rich-switch-buffer-project (:width 15 :face success))
          (ivy-rich-switch-buffer-path (:width (lambda (x) (ivy-rich-switch-buffer-shorten-path x (ivy-rich-minibuffer-width 0.3))))))
         :predicate
         (lambda (cand) (get-buffer cand)))))
```

It looks like
<img width="752" alt="screen shot 2018-07-15 at 11 50 54 am" src="https://user-images.githubusercontent.com/16749790/42730338-5f8c6698-8825-11e8-904e-fd0ac1931126.png">

You can reference to the [README](https://github.com/Yevgnen/ivy-rich/blob/customize/README.org) for more details. Feedback is welcomed.

**Comment by dsvensson** [comment]
It's however an issue with placing the icon column first if the icons don't have the same width. I think it might be possible to do something like the Fira Code ligatures, but I haven't been able to create the correct return value for a variant of your ivy-rich-switch-buffer-icon. Here's how the prettify-symbols-stuff works:

```lisp
(defun fira-code-mode--make-alist (list)
  "Generate prettify-symbols alist from LIST."
  (let ((idx -1))
    (mapcar
     (lambda (s)
       (setq idx (1+ idx))
       (let* ((code (+ #Xe100 idx))
              (width (string-width s))
              (prefix ())
              (suffix '(?\s (Br . Br)))
              (n 1))
         (while (< n width)
           (setq prefix (append prefix '(?\s (Br . Bl))))
           (setq n (1+ n)))
         (cons s (append prefix suffix (list (decode-char 'ucs code))))))
     list)))
```

So it pads with prefix/suffix to make the replacement UTF-8 symbol the correct width, but my elisp-fu is kind of weak so I'm not sure how to pad the icon character in away that works with ivy-rich.

**Comment by honmaple** [comment]
I found another way to work with `all-the-icon-ivy`, and it's simpler
```
  (defun maple/ivy-set-display-transformer (cmd transformer)
    "Advice ivy-set-display-transformer with `CMD` and `TRANSFORMER`."
    (let* ((tf (plist-get ivy--display-transformers-list cmd))
           (tf (if tf `(lambda(str) (,transformer (,tf str))) transformer)))
      (setq ivy--display-transformers-list
            (plist-put ivy--display-transformers-list cmd tf))))

  (advice-add 'ivy-set-display-transformer :override #'maple/ivy-set-display-transformer)
```

**Comment by dsvensson** [comment]
ah... `(ivy-rich-switch-buffer-delimiter "\t")` was what was missing.

**Comment by ianpan870102** [comment]
@Yevgnen  Minor typo: when adding the column `(ivy-rich-switch-buffer-icon :width 2)`, we should wrap the width attribute in parentheses, or else it wouldn't take effect:
```emacs-lisp
(ivy-rich-switch-buffer-icon (:width 2))
```

**Comment by hisnawi** [comment]
I use counsel-projectile-switch-to-buffer and can't see the icons with the above code.
Any resolution on this?

**Comment by MeltWS** [comment]
@hisnawi 
Works for me with the above code.
![image](https://user-images.githubusercontent.com/15630634/73886879-b7773e80-486a-11ea-859c-011d28de78d2.png)
Havn't figured out the issue with the icon spacing yet.

**Comment by cmacrae** [comment]
@MeltWS Would you mind sharing the configuration you've used to get your columns aligned nicely? :pray: I've used the expressions shared in the conversation thus far, but I'm getting some misalignment:  
![image](https://user-images.githubusercontent.com/3392199/73935888-7e29e780-48d9-11ea-8cb9-3755d6cc86bd.png)

**Comment by MeltWS** [comment]
@cmacrae 
```emacs-lisp
  (defun ivy-rich-switch-buffer-icon (candidate)
    (with-current-buffer
   	(get-buffer candidate)
      (let ((icon (all-the-icons-icon-for-mode major-mode)))
	(if (symbolp icon)
	    (all-the-icons-icon-for-mode 'fundamental-mode)
	  icon))))
  (setq ivy-rich-display-transformers-list
	(plist-put ivy-rich-display-transformers-list 'ivy-switch-buffer
		   '(:columns
		     ((ivy-rich-switch-buffer-icon (:width 1))
		      (ivy-rich-candidate (:width 0.25))
		      (ivy-rich-switch-buffer-size (:width 0.05 :face font-lock-comment-face))
		      (ivy-rich-switch-buffer-indicators (:width 0.05 :face error :align right))
		      (ivy-rich-switch-buffer-major-mode (:width 0.1 :face font-lock-function-name-face))
		      (ivy-rich-switch-buffer-project (:width 0.15 :face success))
		      (ivy-rich-switch-buffer-path (:width (lambda (x) (ivy-rich-switch-buffer-shorten-path x (ivy-rich-minibuffer-width 0.4))) :face font-lock-keyword-face)))
		     :predicate
		     (lambda (cand) (get-buffer cand))
		     :delimiter "\t")))
```
You need a delimiter ``"\t"`` for the icons to align properly and then you probably want to lower your tab width.

**Comment by hisnawi** [comment]
I tried that setup and magit-diff icon don't show up anymore.

**Comment by hisnawi** [comment]
> @hisnawi
> Works for me with the above code.
> ![image](https://user-images.githubusercontent.com/15630634/73890966-720b3f00-4873-11ea-8b5c-8f3c64dbda7c.png)
> 
> Using `:delimiter` helps if you have spacing issues as well.

It works now but counsel-find-file doesn't show icons any more "all-the-icons-ivy" is enabled!

**Comment by hisnawi** [comment]
@cmacrae 
With the "\t" delimiter the spacing between the icons and the file name became too big. I don't see your screen shot has this problem. How did you manage to have that with the same setup I copied from you?

**Comment by MeltWS** [comment]
@hisnawi 
> It works now but counsel-find-file doesn't show icons any more "all-the-icons-ivy" is enabled!
> With the "\t" delimiter the spacing between the icons and the file name became too big. I don't see your screen shot has this problem. How did you manage to have that with the same setup I copied from you?

>**you probably want to lower your tab width.**




For counsel you need to add settings with the correct transformer to ``ivy-rich--display-transformers-list``
You probably want ``counsel-projectile-find-file`` and ``counsel-projectile-switch-project`` it depends on what commands you use.

**Comment by hisnawi** [comment]
@MeltWS How do I lower my tab width without affecting tab width when I program?
I just want it to affect the tabs in ivy-rich.
What is your setup in terms of tab width?

**Comment by Yevgnen** [comment]
Something that is related ... [all-the-icons-ivy-rich](https://github.com/seagle0128/all-the-icons-ivy-rich)

**Comment by hisnawi** [comment]
> Something that is related ... [all-the-icons-ivy-rich](https://github.com/seagle0128/all-the-icons-ivy-rich)

Interesting, can't find it on melpa.

**Comment by atkpwn** [comment]
Hi!
If you use all-the-icons-ivy, I combine them with ivy-rich as follows:
```emacs-lisp
(defun all-the-icons-ivy-rich-transformer (s)
  (let* ((icon (all-the-icons-ivy-buffer-transformer s))
         (rich (ivy-rich--ivy-switch-buffer-transformer s))
         (info (substring rich (string-width s) (string-width rich))))
    (concat icon info)))
(ivy-set-display-transformer 'ivy-switch-buffer
                             'all-the-icons-ivy-rich-transformer)
(ivy-set-display-transformer 'counsel-find-file
                             'all-the-icons-ivy-rich-transformer)
```
This will make it add icons to all virtual buffers too. I am not sure if it is a good way to do it, though.

**Comment by Yevgnen** [comment]
@hisnawi It's on Melpa now.

**Comment by seagle0128** [comment]
I released https://github.com/seagle0128/all-the-icons-ivy-rich on Melpa.
