### ISSUE TITLE
Recentf

### ISSUE THREAD

**Issue by igorepst** [Yevgnen/ivy-rich#4]
Hello,
Could you, please, add support for the virtual buffers in ivy; at least, for paths in recentf?
Thank you

**Comment by Yevgnen** [comment]
Hi, do you mean something like #[this](https://github.com/abo-abo/swiper/issues/256) or show the virtual buffer just as `|file name | directory|` ?

**Comment by igorepst** [comment]
More info is better, than less info :) But, seriously, the path would be enough

**Comment by Yevgnen** [comment]
If you just want the path, setting `ivy-virtual-abbreviate` to `'full` should do the trick. 

<img width="644" alt="screen shot 2016-12-17 at 11 28 59 pm" src="https://cloud.githubusercontent.com/assets/16749790/21287904/a2428d1c-c4b0-11e6-9b00-e26a70ee6efe.png">

But I if you want it to to be displayed like the buffers above, I could add an option to make it like 

<img width="645" alt="screen shot 2016-12-17 at 11 26 02 pm" src="https://cloud.githubusercontent.com/assets/16749790/21287881/378ed7fa-c4b0-11e6-9dcd-71e63570d3d2.png">

to keep consistency. I would like to provide more support for `org-ref`, `projectile` to display vc information etc. But currently I've not figured out what information would be necessary.

**Comment by igorepst** [comment]
It seems the second option will be not only more consistent, but prettier. And indeed, it may be optional.
Thanks

**Comment by CSRaghunandan** [comment]
@Yevgnen  I really like the 2nd option more than the first :) I'm a sucker for consistency across my applications.

Also, I feel like `switch-to-buffer` lags a bit after using `ivy-rich` (only when I'm scrolling a lot across the  results). Does the same happen to you?

**Comment by Yevgnen** [comment]
I'll will make a commit for `recentf` soon. 

I don't feel any difference whether I use the package not. The transformation is quite lightweight and only processes the opened buffers now. I tried with 200 opened buffers, with different type files including `python`, `c++`, `emacs-lisp`, `org` etc, but still feel no difference. Maybe you can use the profiler to check ?

**Comment by CSRaghunandan** [comment]
@Yevgnen the difference is only when I scroll down continuously using pressing and holding up or down arrow or `C-n`/`C-p` other than that, I do not notice any slow downs whatsoever.

**Comment by Yevgnen** [comment]
@CSRaghunandan Does this happen with the `emacs -Q` setting? Which kind of buffer have you opened? Is there any unicode char in the file path of the opened buffers ?

**Comment by CSRaghunandan** [comment]
@Yevgnen  It does not happen on `emacs -q`. I guess i've something in my emacs config that causing very minor lag when I scroll continuously when holding down arrows. I guess it's fine for now as I rarely ever continuously scroll in the ivy minibuffer

**Comment by Yevgnen** [comment]
@CSRaghunandan Sorry for late reply. I've tried `js2-mode` buffers but still have no idea how is the issue come and everything me here is just fine. I've push a new commit for the origin issue so I'll close this one. Feel free to open a new issue if you still encounter with the lag problem.

**Comment by igorepst** [comment]
Hi Yevgnen,
Could you, please, look into the issue? I'm getting this:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  propertize(nil face ivy-virtual)
  ivy-rich-switch-buffer-transformer(#("ig-ivy.el" 0 9 (face ivy-virtual)))
  mapcar(ivy-rich-switch-buffer-transformer ("*Help*" "ivy-rich.el" "ivy.el" "*Apropos*" "*scratch*" "*Messages*" "*Backtrace*" #("ig-ivy.el" 0 9 (face ivy-virtual)) #("ig-dired.el" 0 11 (face ivy-virtual))))
  ivy--format(("*Help*" "ivy-rich.el" "ivy.el" "*Apropos*" "*scratch*" "*Messages*" "*Backtrace*" #("ig-ivy.el" 0 9 (face ivy-virtual)) #("ig-dired.el" 0 11 (face ivy-virtual)) #("bytecomp.el.gz" 0 14 (face ivy-virtual)) #("ig-volatile.el" 0 14 (face ivy-virtual)) #("alect-themes.el" 0 15 (face ivy-virtual)) #("dired.el.gz" 0 11 (face ivy-virtual)) #("files.el.gz" 0 11 (face ivy-virtual)) #("data.c" 0 6 (face ivy-virtual)) #("dired-rainbow.el" 0 16 (face ivy-virtual)) #("loaddefs.el" 0 11 (face ivy-virtual)) #(".recentf" 0 8 (face ivy-virtual)) #("ig-install-packages.el" 0 22 (face ivy-virtual)) #("ig-packages.el" 0 14 (face ivy-virtual)) #("ig-hydra.el" 0 11 (face ivy-virtual)) #("subr.el.gz" 0 10 (face ivy-virtual)) #("ig-edit.el" 0 10 (face ivy-virtual)) #("ig-modeline.el" 0 14 (face ivy-virtual)) #("ig-helm.el" 0 10 (face ivy-virtual)) "elisp-info [–]"))
  ivy--exhibit()
  ivy--minibuffer-setup()
  #[0 "\302\303\301\242\"\210\300 \207" [ivy--minibuffer-setup (#0) remove-hook minibuffer-setup-hook] 3]()
  read-from-minibuffer("Switch to buffer: " nil (keymap (keymap) keymap (3 keymap (1 . ivy-toggle-ignore) (15 . ivy-occur)) (67108903 . ivy-avy) (33554464 . ivy-restrict-to-matches) (15 . hydra-ivy/body) (7 . minibuffer-keyboard-quit) (32 . self-insert-command) (18 . ivy-reverse-i-search) (19 . ivy-next-line-or-history) (remap keymap (describe-mode . ivy-help) (kill-ring-save . ivy-kill-ring-save) (kill-line . ivy-kill-line) (scroll-down-command . ivy-scroll-down-command) (scroll-up-command . ivy-scroll-up-command) (end-of-buffer . ivy-end-of-buffer) (beginning-of-buffer . ivy-beginning-of-buffer) (kill-word . ivy-kill-word) (forward-char . ivy-forward-char) (delete-char . ivy-delete-char) (backward-kill-word . ivy-backward-kill-word) (backward-delete-char-untabify . ivy-backward-delete-char) (delete-backward-char . ivy-backward-delete-char) (previous-line . ivy-previous-line) (next-line . ivy-next-line)) (9 . ivy-partial-or-done) (10 . ivy-alt-done) (27 keymap (1 . ivy-read-action) (15 . ivy-dispatching-call) (111 . ivy-dispatching-done) (105 . ivy-insert-current) (106 . ivy-yank-word) (114 . ivy-toggle-regexp-quote) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (10 . ivy-immediate-done) (13 . ivy-call)) (13 . ivy-done)) nil ivy-history)
  ivy-read("Switch to buffer: " internal-complete-buffer :matcher ivy--switch-buffer-matcher :preselect "ivy-rich.el" :action ivy--switch-buffer-action :keymap (keymap) :caller ivy-switch-buffer)
  ivy-switch-buffer()
  funcall-interactively(ivy-switch-buffer)
  call-interactively(ivy-switch-buffer nil nil)
  command-execute(ivy-switch-buffer)
```
My config:
```
  (use-package ivy-rich
    :diminish ""
    :init
    (setq ivy-rich-switch-buffer-align-virtual-buffer t)
    (ivy-set-display-transformer 'ivy-switch-buffer 'ivy-rich-switch-buffer-transformer))
```

**Comment by Yevgnen** [comment]
@igorepst 

Base on the error `ivy-rich-switch-buffer-transformer(#("ig-ivy.el" 0 9 (face ivy-virtual)))`, have you set `ivy-virtual-abbreviate` to `full`? Looks like I should add more condition to handle this situation. To align the virtual buffers, we need 

```
(setq ivy-virtual-abbreviate 'full
      ivy-rich-switch-buffer-align-virtual-buffer t)
```

**Comment by igorepst** [comment]
@Yevgnen 
Thank you! I forgot about this setting
