### ISSUE TITLE
Should ignore :advice info

### ISSUE THREAD

**Issue by seagle0128** [Yevgnen/ivy-rich#44]
Hi,

If adding advice for a function, the first line is the advice information, I think it's should be trim and find the actual first line in the comments. Your opinion?

![image](https://user-images.githubusercontent.com/140797/49034259-5eceff00-f1ec-11e8-862d-7e4a12abbf75.png)

**Comment by Yevgnen** [comment]
Sorry for late reply. Thanks for reporting. Should fixed in next build.

**Comment by seagle0128** [comment]
Thanks for fixing it!
