### ISSUE TITLE
ivy-rich--display-transformers-list naming is confusing

### ISSUE THREAD

**Issue by noctuid** [Yevgnen/ivy-rich#45]
Since `ivy-rich--display-transformers-list` is defined with `defcustom` and is meant to be customized by the user (based on documentation), it should not be marked as an internal variable with `--`. I think it would make sense to rename it to `ivy-rich-display-transformers-list` to avoid confusion and then use `define-obsolete-variable-alias` to keep the package working with the old variable.

**Comment by Yevgnen** [comment]
Great point! I will make a patch soon! Thank you!
