### ISSUE TITLE
Use buffer-local-value instead of with-current-buffer

### ISSUE THREAD

**Issue by dakra** [Yevgnen/ivy-rich#46]
Just saw [this link](https://github.com/alphapapa/emacs-package-dev-handbook#best-practices).
As `ivy-rich` uses a lot of `with-current-buffer` and speed for ivy
is important, maybe it's a good idea to switch whenever possible to `buffer-local-value`?

**Comment by Yevgnen** [comment]
Hi, thanks for the link. I will look into it later. Though currently most speed issue of `ivy-rich` come from `projectile`, setting `projectile-project-root-files-functions` could give huge speed up.

**Comment by Yevgnen** [comment]
Hi, it seems that quite a bit place can be switched to `buffer-local-value`. Do you known whether it's possible to perform the same trick when executing functions?

**Comment by dakra** [comment]
> Do you known whether it's possible to perform the same trick when executing functions?

Sorry, don't know. i would guess not but I have no idea and didn't research it.
