### ISSUE TITLE
Slow with tramp

### ISSUE THREAD

**Issue by seagle0128** [Yevgnen/ivy-rich#47]
It's slow to switching buffers while using tramp, even set `ivy-rich-parse-remote-buffer` to nil.

Refer to https://github.com/Yevgnen/ivy-rich/issues/23

![emacs](https://user-images.githubusercontent.com/140797/50740733-d6ea0500-122d-11e9-9783-bf9f90f4f355.gif)

![image](https://user-images.githubusercontent.com/140797/50920075-676b5400-147f-11e9-80cb-eaf5e31504f8.png)

**Comment by Yevgnen** [comment]
Hi, thanks for the information in #23. I've tried to minimize the usages of `file-truename` in a new branch `optimize`. At least it should work with `ivy-rich-parse-remote-buffer` setting to `nil`... Maybe it's buggy, could you please help me test it if you have time? Thanks.

**Comment by Yevgnen** [comment]
I've merged it to master.

**Comment by yuezhu** [comment]
I'm having the same issue as well. Both `ivy-rich-parse-remote-buffer` and `ivy-rich-parse-remote-file-path` are setting to `nil`. Even with that when switching buffers with a tramp buffers being opened, there is an obvious lag/slowdown that can be observed, while that does not happen without a tramp buffer.

My `ivy-rich` configuration is basic (I'm using `use-package`):

In `init.el`
```
(use-package ivy-rich
  :ensure t
  :after (ivy counsel)
  :config
  (ivy-rich-mode 1))
```

In `custom.el`
```
....
 '(ivy-rich-parse-remote-buffer nil)
 '(ivy-rich-parse-remote-file-path nil)
 '(ivy-rich-path-style (quote full))
....
```

**Comment by Yevgnen** [comment]
Have you tried the latest master version?

**Comment by seagle0128** [comment]
It's much better than before. I am closing it.

**Comment by Ergus** [comment]
I have observed a very slow responsiveness when using ivy-switch-buffer + tramp + ivy-rich.
When opening one file it is fine, but with 2 or more remote files open it freezes and produces very long pauses (2-4 seconds) for a simple ivy-next-line.

I ran a profile (just C-x b and some C-n or C-p ) and the output was as you can see in the image:

![Screenshot_2019-03-28_11-42-11](https://user-images.githubusercontent.com/6975176/55168353-f6c8ff00-5172-11e9-93ae-9c026dcbfc81.png)
![Screenshot_2019-03-28_12-01-40](https://user-images.githubusercontent.com/6975176/55168354-f6c8ff00-5172-11e9-9e0e-43b38b73de9d.png)

The ivy-rich version I have is 20190307. I reported thin to abo-abo in swiper , and he redirected me to report it here.

**Comment by seagle0128** [comment]
It seems that `project-current` has bad performance sometimes.

**Comment by Yevgnen** [comment]
@Ergus `project.el` seems pretty slow than `projectile` on my machine. Are you using the master version? Maybe you can try `(setq ivy-rich-parse-remote-buffer nil)` if you have a slow `tramp` connection?

**Comment by Ergus** [comment]
@Yevgnen  my tramp connection is not properly slow, that's what made me add the issue. Any way, I use projectile and counsel-projectile actually, so is it there an option to tell ivy-rich to use projectile instead?

**Comment by Yevgnen** [comment]
@Ergus `ivy-rich` should have tried `projectile` first [here](https://github.com/Yevgnen/ivy-rich/blob/master/ivy-rich.el#L323) if you've enabled `projectile-mode`. I'm not quite familiar with `projectile` but it seems that it used to have many performance issues before when reading into the issue list. So currently based on my poor experiences, I can no give any suggestion...

**Comment by seagle0128** [comment]
@Yevgnen I have some comments for the codes of finding the project root directory.

1. If failed to get project root or nil, should use `default-directory`.
1. It's very slow to get the project root sometimes. It's not necessary to get it very time. Since the project root is fixed after opening the file generally, it can be cached for better performance. 

I did the similar optimization in `doom-modeline` (https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-core.el#L478).
