### ISSUE TITLE
`counsel-describe-function` does not work well with `ivy-display-function-lv`

### ISSUE THREAD

**Issue by AmaiKinono** [Yevgnen/ivy-rich#62]
Hi. I use `ivy-display-function-lv` as shown in the swiper wiki:

``` emacs-lisp
(require 'lv)

(defun ivy-display-function-lv (text)
  (let ((lv-force-update t))
    (lv-message
     (if (string-match "\\`\n" text)
         (substring text 1)
       text))))

(setq ivy-display-functions-alist '((t . ivy-display-function-lv)))
```

When using ivy-rich, calling `counsel-describe-function` makes an error:

```
Error in post-command-hook (ivy--queue-exhibit): (error "Not enough arguments for format string")
```

It works well with the default display function.

**Comment by Yevgnen** [comment]
Sorry for late reply. Does it happen immediately after you call `counsel-describe-function`, or after you type something when invoking `counsel-describe-function`?

**Comment by Yevgnen** [comment]
Well, it seems it's a bug in `ivy`, I test it in an `emacs -q` without `ivy-rich` and the issue still there.

**Comment by AmaiKinono** [comment]
Yes, my fault. I'll close this issue and report it to the author.
