### ISSUE TITLE
[Feature Request] counsel-bookmark support w3m file type

### ISSUE THREAD

**Issue by dunkarooftop** [Yevgnen/ivy-rich#67]
https://i.imgur.com/vIyvY5B.jpg

right now it use a unknown font which look out of place. Thanks :)

**Comment by Yevgnen** [comment]
Will fix it soon, please wait!

**Comment by dunkarooftop** [comment]
[iosevka](https://github.com/be5invis/Iosevka) is the font. Thanks for the fix :)
