### ISSUE TITLE
Error on switching buffer (when package-menu-mode is active)

### ISSUE THREAD

**Issue by ianpan870102** [Yevgnen/ivy-rich#71]
If I have \*Packages\* as an active buffer, Emacs throws `Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp package-menu-mode)` immediately when I try to switch buffer
By kililing the \*Packages\* buffer, switching buffers work perfectly again.

Disabling ivy-rich will prevents this error altogether, therefore I suspect this is due to the way ivy-rich handles the docstring for package-menu-mode.

**Comment by Yevgnen** [comment]
It does not happen on my emacs 26.3. What's you emacs version and `ivy-rich` version. I notice that you maybe using the `customize` branch as you mentioned in another issue?

**Comment by ianpan870102** [comment]
I was just browsing through documentation of different branches but I did install the ivy-rich package from MELPA, so it's the master branch I believe.
I'm using Emacs 27.0.50 on macOS, and for the past two days, the issue seems to be gone. I will close this for now and perhaps reopen it if the problem resurfaces. Thanks for getting back!
