### ISSUE TITLE
switch-buffer broken on Melpa Stable

### ISSUE THREAD

**Issue by ScottFreeCode** [Yevgnen/ivy-rich#73]
Need to release a new tag so that #52 is published.

**Comment by ScottFreeCode** [comment]
By the way, I forgot to mention this is one of the best packages I've found since I discovered which-key and ivy/counsel. I often no longer have to pull up help for functions as I'm searching through them, just to see a basic concept of what they do!

Thank you for making my Emacs experience that much better!

**Comment by Yevgnen** [comment]
Hi, thanks for the kind words. I'm not sure what does 'so that #52 is published'... and how can I help?

**Comment by ScottFreeCode** [comment]
The fix in pull request #52 prevents the ivy/counsel switch buffers commands from breaking due to the 'cl- prefix. It wasn't in version 0.1.4, but now that it's in 0.1.5 I can switch this package back to melpa-stable. Thanks!!
