### ISSUE TITLE
Args out of rang

### ISSUE THREAD

**Issue by xianghx** [Yevgnen/ivy-rich#8]
ivy-rich-switch-buffer-transformer: Args out of range: "/home/xianghx/dotconfig/.emacs.d", 33, nil

```lisp
(use-package ivy-rich
  :ensure t
  :defer t
  :init
  (setq ivy-rich-switch-buffer-name-max-length 48)
  (ivy-set-display-transformer 'ivy-switch-buffer 'ivy-rich-switch-buffer-transformer)
  )
```

**Comment by xianghx** [comment]
GNU Emacs 25.1.1 (i686-pc-linux-gnu, GTK+ Version 3.10.8) of 2016-09-24
other is latest.

ivy-rich-switch-buffer-transformer: Args out of range: "/home/xianghx/.emacs.d", 23, nil

**Comment by adouzzy** [comment]
I had the same problem from time to time. I will post again if I can reproduce it too.

**Comment by ambihelical** [comment]
I also have this problem, but I can reproduce it.  The problem starts after I open a deft buffer at /home/work/Dropfile/Notes which is outside of my current projectile project which is at /home/work/dev/dotfiles. 

 Here is a partial backtrace:

Debugger entered--Lisp error: (args-out-of-range "/home/work/Dropbox/Notes" 25 nil)
  substring-no-properties("/home/work/Dropbox/Notes" 25)
  ivy-rich-switch-buffer-path(#("Notes          " 0 15 (face success)))
  ivy-rich-switch-buffer-transformer("*Deft*")
  mapcar(ivy-rich-switch-buffer-transformer ("*scratch*" "*Messages*" "*Deft*" #("/home/work/dev/dotfiles/emacs.d/elpa/ivy-rich-20170517.554/ivy-rich.el" 0 70 (face ivy-virtual)) #("/home/work/dev/dotfiles/emacs.d/init.el" 0 39 (face ivy-virtual)) #("/home/work/dev/dotfiles/emacs.d/lisp/utilities.el" 0 49 (face ivy-virtual)) #("/usr/local/share/emacs/25.2/lisp/savehist.el.gz" 0 47 (face ivy-virtual)) #("/usr/local/share/emacs/25.2/lisp/mb-depth.el.gz" 0 47 (face ivy-virtual)) #("/usr/local/share/emacs/25.2/lisp/textmodes/flyspell.el.gz" 0 57 (face ivy-virtual)) #("/usr/local/share/emacs/25.2/lisp/textmodes/ispell.el.gz" 0 55 (face ivy-virtual)) #("/home/work/extern/emacs-25.2/src/xdisp.c" 0 40 (face ivy-virtual)) #("/usr/local/share/emacs/25.2/lisp/subr.el.gz" 0 43 (face ivy-virtual)) #("/home/work/dev/dotfiles/emacs.d/elpa/use-package-20170710.1234/use-package.el" 0 77 (face ivy-virtual)) #("/usr/local/share/emacs/25.2/lisp/font-core.el.gz" 0 48 (face ivy-virtual)) #("/usr/local/share/emacs/25.2/lisp/composite.el.gz" 0 48 (face ivy-virtual)) #("/usr/local/share/emacs/25.2/lisp/gnus/smiley.el.gz" 0 50 (face ivy-virtual)) #("/home/work/.emacs.d/elpa/ivy-rich-20170517.554/ivy-rich-autoloads.el" 0 68 (face ivy-virtual))))

**Comment by ambihelical** [comment]
My versions, if needed:
ivy-20170703.2350
ivy-rich-20170517.554
