### ISSUE TITLE
Symbol’s value as variable is void: ivy--display-transformers-list

### ISSUE THREAD

**Issue by gdindi** [Yevgnen/ivy-rich#81]
Hi,

After upgrading Ivy to today's version on MELPA, I get the following error when activating ivy-rich-mode:

Symbol’s value as variable is void: ivy--display-transformers-list

I understand that [this commit](https://github.com/abo-abo/swiper/commit/98c61dec812c3a3f227e71a59e004d2d90593130) has marked it as obsolete.

**Comment by Yevgnen** [comment]
I believe #80 fixed the issue, let me know if it didn't :)
