### ISSUE TITLE
Column :align behavior is backwards

### ISSUE THREAD

**Issue by jeffvalk** [Yevgnen/ivy-rich#97]
Setting a transformer column's `:align` property in `ivy-rich-display-transformers-list` aligns text backwards from the semantics:

- Setting `:align` to `'left` will **right**-align the column.
- Setting `:align` to any other value will **left**-align the column.

This seems to be because the function `ivy-rich-normalize-width` interprets its `left` argument as "pad on the left" rather than "align to the left".

**Comment by Yevgnen** [comment]
That's awkward... Thanks for reporting this.

**Comment by jeffvalk** [comment]
It had me puzzled for a few minutes. :slightly_smiling_face: 

In fixing this, it might be good to change the `left` argument's name and the docstring in `ivy-rich-normalize-width` too.

**Comment by Yevgnen** [comment]
Should be clearer now 😅
